### ISSUE TITLE
v3.0.0 broke sheet() using extract

### ISSUE THREAD

**Issue by TheBosZ** [streamich/nano-css#189]
I can't figure out exactly why, but v3.0.0 broke my plugin: https://bitbucket.org/TheBosZ/rollup-plugin-nano-css/

With 2.2.0, all tests pass, but with 3.0.0, calling `nano.sheet` returns an empty object instead of the expected string of class names.

**Comment by streamich** [comment]
I need some code to replicate that behaviour, to be able to fix that.

**Comment by TheBosZ** [comment]
Sorry, the tests on that project replicate it but I can pull them out into an example if you'd like.

**Comment by TheBosZ** [comment]
It looks like the extract addon is no longer forcing the lazy load of sheet.

**Comment by TheBosZ** [comment]
This repo can show the issue: https://github.com/TheBosZ/nano-css-problems/

Run: `npm i && npm run extract`

The sheet has the `button` property, but the resulting object no longer has the property.

In 2.2.0, the object returned from `sheet()` was already loaded. Now it's back to being lazy-loaded.

**Comment by streamich** [comment]
This https://github.com/streamich/nano-css/pull/190 should fix your problem.

**Comment by TheBosZ** [comment]
Perfect! 3.0.1 solves the bug!
