### ISSUE TITLE
Why useStyles is not a hook?

### ISSUE THREAD

**Issue by dy** [streamich/nano-css#230]
According to [react convention](https://reactjs.org/docs/hooks-rules.html), components starting with use- prefix are hooks.
That's a bit confusing that this component is called like hook but indeed it is not.

Would be nice to just
```js
props => {
let classes = useStyles({
root: {...},
secondary: {...}
})

return <div className={classes.root}></div>
}
```

**Comment by streamich** [comment]
`useStyles` is not a hook because it was created before React released Hooks.

**Comment by streamich** [comment]
There is [`useCss` hook](https://github.com/streamich/react-use/blob/master/docs/useCss.md) though, which does Virtual CSSOM.
