### ISSUE TITLE
Remove leading space

### ISSUE THREAD

**Issue by RobbieTheWagner** [streamich/nano-css#234]
Firstly, great work on this library! It's the smallest and most performant CSSinJS solution that I have found so far!

Is there any way to remove the leading space from the generated class name other than always having to manually trim them?

I feel like it would be easier for those using in React concatenating to just add a space. Whenever I try to use it with `classList.add` on a normal element, it blows up because of the leading space.

**Comment by streamich** [comment]
Sorry, currently no plans to remove leading space.
