### ISSUE TITLE
MIT license missing copyright line

### ISSUE THREAD

**Issue by olivierlacan** [streamich/nano-css#248]
Just a heads up that [your license](https://github.com/streamich/nano-css/blob/017a594e0b8198be8348f652e4fc108a4a9e5a50/LICENSE) is missing a copyright section per: 
- https://choosealicense.com/licenses/mit/
- https://opensource.stackexchange.com/questions/7669/how-should-i-use-software-under-the-mit-licence-without-copyright-holder

An MIT license without a copyright is considered anonymous work which is fine but is that your intent?

**Comment by noahnu** [comment]
I don't believe this project uses an MIT license but rather "The Unlicense": https://unlicense.org/

Either way, it'd be nice to add the unlicense to the package.json via the license property: https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license

**Comment by streamich** [comment]
Thanks,

Indeed, it is useing [Unlicense license](https://spdx.org/licenses/Unlicense.html).

I've added the license to `package.json`.
