### ISSUE TITLE
Replace deprecated `sourcemap-codec`

### ISSUE THREAD

**Issue by harryzcy** [streamich/nano-css#260]
[`sourcemap-codec`](https://www.npmjs.com/package/sourcemap-codec) is not maintained and deprecated. The author documented that it should be replaced by `@jridgewell/sourcemap-codec` instead.

**Comment by kevinashworth** [comment]
+1. 

I am seeing this warning:
`npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead`
